name: my_quotes
description: Mobile app for storing personal quotes

version: 1.2.1+121

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: 4.0.5
  get_it: 4.0.1
  rxdart: 0.24.0
  hive: 1.4.1+1
  path_provider: 1.6.7
  share: 0.6.4
  url_launcher: 5.4.5

dev_dependencies:
  pedantic: 1.9.0
  hive_generator: 0.7.0+2
  build_runner:

flutter:
  uses-material-design: true

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/icons/icomoon.ttf
